language: python
services:
  - docker
install:
  - make deps
script:
  - make test
  - make lint
  - make docker_build
  - make docker_push
deploy:
 provider: heroku
 app: dry-oasis-08559
 api_key: ${HEROKU_API_KEY}
